title: Plateforme de Protection des Lanceurs d'Alerte en Afrique
email: info@pplaaf.org
baseurl: /pplaaf
url: "https://pplaaf.org"

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

collections:
  ngos:
  board:
  journalists:
  management:
  studies:
    output: true
    permalink: :name.html
  profiles:
    output: true
    permalink: :name.html